# Generated by Django 2.1.4 on 2018-12-09 11:39

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('seo_title', models.CharField(blank=True, max_length=220, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, max_length=220, null=True, verbose_name='SEO описание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='название ссылки')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('comments_open', models.BooleanField(default=True, verbose_name='Комментарии открыты')),
                ('seo_title', models.CharField(blank=True, max_length=220, null=True)),
                ('seo_description', models.TextField(blank=True, max_length=220, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-pub_date'],
            },
        ),
    ]
