# Generated by Django 2.1.4 on 2018-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181209_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_seo_title', models.CharField(blank=True, max_length=140, null=True, verbose_name='SEO заголовок главной страницы')),
                ('main_seo_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO описание главной страницы')),
                ('top_selling_products', models.ManyToManyField(to='store.Product', verbose_name='Выберите самые продаваемые товары')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
            },
        ),
    ]
