# Generated by Django 2.1.4 on 2018-12-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_siteconfiguration_menu_category_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='menu_category_items',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='menu_category_items',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='store.Category', verbose_name='Категории включенные в меню'),
        ),
    ]
