# Generated by Django 2.1.4 on 2018-12-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20181210_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_adress',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Адрес интернет магазина'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Электронная почта интернет магазина'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона интернет магазина'),
        ),
    ]
