# Generated by Django 2.1.4 on 2018-12-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_auto_20181210_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Итоговая сумма')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=18, verbose_name='Ваш номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ваш e-mail')),
                ('buying_type', models.CharField(blank=True, choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Доставка', max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True, verbose_name='Город доставки')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес доставки')),
                ('notes', models.TextField(verbose_name='Пожелания')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Итоговая сумма заказа')),
                ('items', models.ManyToManyField(to='orders.Cart')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='store.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='orders.OrderItem', verbose_name='cart_items'),
        ),
    ]
