# Generated by Django 2.1.4 on 2018-12-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181224_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='orders.OrderItem', verbose_name='Товары в корзине'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='orders.Cart', verbose_name='Корзина этого заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Принят в обработку', 'Принят в обработку'), ('Выполняется', 'Выполняется')], default='Принят в обработку', max_length=100),
        ),
    ]
