# Generated by Django 2.1.4 on 2018-12-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181224_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_items', to='orders.Cart', verbose_name='Корзина этого заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Выполняется', 'Выполняется'), ('Принят в обработку', 'Принят в обработку')], default='Принят в обработку', max_length=100),
        ),
    ]
