# Generated by Django 2.1.4 on 2018-12-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181224_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Выполняется', 'Выполняется'), ('Принят в обработку', 'Принят в обработку'), ('Оплачен', 'Оплачен')], default='Принят в обработку', max_length=100),
        ),
    ]
